<?php
function ybf_hooker_views_pre_render(&$view) {
  if ($view->name == 'annual' && $view->current_display == 'page') {
      if (isset($view->result[0]->nid)) {
      $last_year_nid = $view->result[0]->nid;
      drupal_goto('node/'.$last_year_nid); 
    }
  }

}
function ybf_hooker_init() {
  drupal_add_css(drupal_get_path('theme', 'ybf').'/css/dev.css');
  if ($_GET['q'] == 'project/other') {
    drupal_set_title('โครงการที่ร่วมกับภาคีต่างๆ เพื่อเป็นกลไกขยายผลและสร้างผลลัพธ์ทางสังคม');
  }
}

function ybf_hooker_menu() {
  $items = array();
  $items['setting/project-description'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Setting Project Description', //page title
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('setting_project_descption_form'), //put the name of the form here
    'access arguments' => array('edit project description')
  );
  return $items;
}
function setting_project_descption_form($form, &$form_state) {
  $form['project_description'] = array(
    '#type' => 'textarea',
    '#title' => 'Project descption',
    '#default_value' => variable_get('project_description')
  );
  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  return $form;
}

function setting_project_descption_form_submit($form, &$form_state) {
   variable_set('project_description', $form['project_description']['#value']); 
}

function ybf_hooker_permission() {
  return array(
    'edit project description' => array(
      'title' => t('Edit project description'),
    ),
  );
}
function ybf_hooker_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'webform_client_form_404') {
    $form['submitted']['comment_junior']['#access'] = False;
    $form['submitted']['comment_secondary']['#access'] = False;
    $form['submitted']['comment_knowourselves']['#access'] = False;
    $form['submitted']['comment_occupation']['#access'] = False;
    $form['submitted']['comment_future']['#access'] = False;
    $form['#submit'][] = 'webform_knowourselves_submit';
  }
  if ($form_id == 'ybf_comment_knowourselves_form') {
    if (!isset($_SESSION['webform_knowourselves_sid'])) {
       drupal_set_message('กรุณาลงทะเบียนก่อนทำแบบสอบถามค่ะ', 'error');
       drupal_goto('highschool/knowourselves');
      
    }
    drupal_add_js("

      jQuery(document).ajaxComplete(function(){
        console.log('form submit success');
        if (!$('#comment_form').find('.error').length) {
          $('#comment_form').find('.section-thanks').show();
          $('#comment_form').find('.section-comment-form').hide();
        
        }
      });

    ", 'inline');

  }

}
function webform_knowourselves_submit(&$form, &$form_state) {
  $_SESSION['webform_knowourselves_sid'] = $form_state['values']['details']['sid'];

}
function ybf_comment_knowourselves_form($form, &$form_state) {
  $form["wrapper"] = array("#markup" => "<div id='comment-ajax'></div>");
  $form['comment'] = array(
    '#type' => 'textarea',
    '#title' => 'แสดงความคิดเห็น',
    '#required' => True,
    '#attributes' => array(
      'placeholder' => 'พิมพ์ข้อความแสดงความคิดเห็น'
    )
  );
  $form['comment_to_field'] = array(
    '#type' => 'hidden'
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'ตกลง',
    '#ajax' => array(
      'callback' => 'comment_knowourselves_form_ajax_handler',
      'effect' => 'fade',
      'wrapper' => 'comment-ajax',
    ),
  );
  $form['cancel'] = array(
    '#type' => 'button',
    '#value' => 'ยกเลิก',
  );
  $form['#attached']['js'] = array(
    'data' => '',
    'type' => 'inline'
  );

  return $form;
}
function comment_knowourselves_form_ajax_handler(&$form, &$form_state) {
  $comment = $form_state['values']['comment'];
  $comment_to_field = $form_state['values']['comment_to_field'];

  // Update comment
  module_load_include('inc', 'webform', 'includes/webform.submissions');
  $submission = webform_get_submission(404, $_SESSION['webform_knowourselves_sid']);
  $submission->data[$comment_to_field][0] = $comment;
  $node = node_load(404);
  webform_submission_update($node, $submission);

  if ($comment != '') {

  }
  return "<div id='comment-ajax'></div>";

}
